export const athlete = [
  {
    athlete_id: 1,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 10,
    name: 'Fermin',
    surname: 'Cacho',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 11,
    name: 'Evelyn',
    surname: 'Ashford',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 12,
    name: 'Yolanda',
    surname: 'Gail',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 13,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 14,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 15,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 16,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 17,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 18,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 2,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 3,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 4,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 5,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 6,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 7,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 8,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
  {
    athlete_id: 9,
    name: 'Arianna',
    surname: 'Fontana',
    bio: 'bio',
    date_of_birth: '14/04/1990',
    weight: 63,
    height: 164,
    photo_id: 1,
  },
];
