export const data = [
  {
    game_id: 4,
    city: 'Pyeongchang',
    year: 2018,
    athlete_id: '1',
    gold: 1,
    silver: 1,
    bronze: 1,
  },
  {
    game_id: 2,
    city: 'Rio de Janeiro',
    year: 2016,
    athlete_id: '2',
    gold: 0,
    silver: 0,
    bronze: 1,
  },
  {
    game_id: 2,
    city: 'Rio de Janeiro',
    year: 2016,
    athlete_id: '3',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 2,
    city: 'Rio de Janeiro',
    year: 2016,
    athlete_id: '4',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 2,
    city: 'Rio de Janeiro',
    year: 2016,
    athlete_id: '5',
    gold: 3,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 2,
    city: 'Rio de Janeiro',
    year: 2016,
    athlete_id: '17',
    gold: 5,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 5,
    city: 'Sochi',
    year: 2014,
    athlete_id: '1',
    gold: 0,
    silver: 1,
    bronze: 2,
  },
  {
    game_id: 5,
    city: 'Sochi',
    year: 2014,
    athlete_id: '18',
    gold: 0,
    silver: 1,
    bronze: 1,
  },
  {
    game_id: 3,
    city: 'London',
    year: 2012,
    athlete_id: '2',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 3,
    city: 'London',
    year: 2012,
    athlete_id: '4',
    gold: 1,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 3,
    city: 'London',
    year: 2012,
    athlete_id: '5',
    gold: 3,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 3,
    city: 'London',
    year: 2012,
    athlete_id: '7',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 3,
    city: 'London',
    year: 2012,
    athlete_id: '17',
    gold: 4,
    silver: 2,
    bronze: 0,
  },
  {
    game_id: 6,
    city: 'Vancouver',
    year: 2010,
    athlete_id: '1',
    gold: 0,
    silver: 0,
    bronze: 1,
  },
  {
    game_id: 8,
    city: 'Beijing',
    year: 2008,
    athlete_id: '2',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 8,
    city: 'Beijing',
    year: 2008,
    athlete_id: '5',
    gold: 2,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 8,
    city: 'Beijing',
    year: 2008,
    athlete_id: '13',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 8,
    city: 'Beijing',
    year: 2008,
    athlete_id: '17',
    gold: 8,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 7,
    city: 'Turin',
    year: 2006,
    athlete_id: '1',
    gold: 0,
    silver: 0,
    bronze: 1,
  },
  {
    game_id: 9,
    city: 'Athens',
    year: 2004,
    athlete_id: '16',
    gold: 2,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 9,
    city: 'Athens',
    year: 2004,
    athlete_id: '17',
    gold: 6,
    silver: 0,
    bronze: 2,
  },
  {
    game_id: 11,
    city: 'Sydney',
    year: 2000,
    athlete_id: '13',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 11,
    city: 'Sydney',
    year: 2000,
    athlete_id: '14',
    gold: 2,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 11,
    city: 'Sydney',
    year: 2000,
    athlete_id: '16',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 11,
    city: 'Sydney',
    year: 2000,
    athlete_id: '15',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 13,
    city: 'Atlanta',
    year: 1996,
    athlete_id: '8',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 13,
    city: 'Atlanta',
    year: 1996,
    athlete_id: '10',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 13,
    city: 'Atlanta',
    year: 1996,
    athlete_id: '12',
    gold: 2,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 13,
    city: 'Atlanta',
    year: 1996,
    athlete_id: '15',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 14,
    city: 'Barcelona',
    year: 1992,
    athlete_id: '8',
    gold: 2,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 14,
    city: 'Barcelona',
    year: 1992,
    athlete_id: '10',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 14,
    city: 'Barcelona',
    year: 1992,
    athlete_id: '11',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 14,
    city: 'Barcelona',
    year: 1992,
    athlete_id: '12',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 14,
    city: 'Barcelona',
    year: 1992,
    athlete_id: '15',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 15,
    city: 'Seoul',
    year: 1988,
    athlete_id: '8',
    gold: 2,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 15,
    city: 'Seoul',
    year: 1988,
    athlete_id: '9',
    gold: 0,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 15,
    city: 'Seoul',
    year: 1988,
    athlete_id: '11',
    gold: 1,
    silver: 1,
    bronze: 0,
  },
  {
    game_id: 15,
    city: 'Seoul',
    year: 1988,
    athlete_id: '15',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 16,
    city: 'Los Angeles',
    year: 1984,
    athlete_id: '8',
    gold: 4,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 16,
    city: 'Los Angeles',
    year: 1984,
    athlete_id: '9',
    gold: 1,
    silver: 0,
    bronze: 0,
  },
  {
    game_id: 16,
    city: 'Los Angeles',
    year: 1984,
    athlete_id: '11',
    gold: 2,
    silver: 0,
    bronze: 0,
  },
];
